// <auto-generated />
using System;
using HomebreweryShoppingAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomebreweryShoppingAssistant.Migrations
{
	[DbContext(typeof(AppDbContext))]
	[Migration("20231031163629_deletedProductDescription")]
	partial class deletedProductDescription
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.13")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Category", b =>
				{
					b.Property<int>("CategoryID")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

					b.Property<int>("CategoryName")
						.HasColumnType("int");

					b.HasKey("CategoryID");

					b.ToTable("Category");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Company", b =>
				{
					b.Property<int>("CompanyID")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

					b.Property<string>("CompanyName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("CompanyID");

					b.ToTable("Company");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Product", b =>
				{
					b.Property<int>("ProductID")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

					b.Property<int>("CategoryID")
						.HasColumnType("int");

					b.Property<int>("CompanyID")
						.HasColumnType("int");

					b.Property<bool>("IsAvailable")
						.HasColumnType("bit");

					b.Property<string>("Product30DaysPrice")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("ProductCheckHistoryID")
						.HasColumnType("int");

					b.Property<string>("ProductLink")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ProductName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ProductPrice")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ShopID")
						.HasColumnType("int");

					b.HasKey("ProductID");

					b.HasIndex("CategoryID");

					b.HasIndex("CompanyID");

					b.HasIndex("ProductCheckHistoryID");

					b.HasIndex("ShopID");

					b.ToTable("Product");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.ProductCheckHistory", b =>
				{
					b.Property<int>("ProductCheckHistoryID")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCheckHistoryID"));

					b.Property<DateTime>("CheckDateTime")
						.HasColumnType("datetime2");

					b.Property<int>("ProductID")
						.HasColumnType("int");

					b.HasKey("ProductCheckHistoryID");

					b.ToTable("ProductCheckHistory");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Shop", b =>
				{
					b.Property<int>("ShopID")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopID"));

					b.Property<string>("ShopLink")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ShopName")
						.HasColumnType("int");

					b.HasKey("ShopID");

					b.ToTable("Shop");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.ShopCheckHistory", b =>
				{
					b.Property<int>("ShopCheckHistoryID")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopCheckHistoryID"));

					b.Property<DateTime>("CheckDateTime")
						.HasColumnType("datetime2");

					b.Property<int>("ShopID")
						.HasColumnType("int");

					b.HasKey("ShopCheckHistoryID");

					b.HasIndex("ShopID");

					b.ToTable("ShopCheckHistory");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Product", b =>
				{
					b.HasOne("HomebreweryShoppingAssistant.Models.Category", "Category")
						.WithMany("Product")
						.HasForeignKey("CategoryID")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("HomebreweryShoppingAssistant.Models.Company", "Company")
						.WithMany("Products")
						.HasForeignKey("CompanyID")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("HomebreweryShoppingAssistant.Models.ProductCheckHistory", null)
						.WithMany("Product")
						.HasForeignKey("ProductCheckHistoryID");

					b.HasOne("HomebreweryShoppingAssistant.Models.Shop", "Shop")
						.WithMany("Product")
						.HasForeignKey("ShopID")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Category");

					b.Navigation("Company");

					b.Navigation("Shop");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.ShopCheckHistory", b =>
				{
					b.HasOne("HomebreweryShoppingAssistant.Models.Shop", "Shop")
						.WithMany()
						.HasForeignKey("ShopID")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Shop");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Category", b =>
				{
					b.Navigation("Product");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Company", b =>
				{
					b.Navigation("Products");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.ProductCheckHistory", b =>
				{
					b.Navigation("Product");
				});

			modelBuilder.Entity("HomebreweryShoppingAssistant.Models.Shop", b =>
				{
					b.Navigation("Product");
				});
#pragma warning restore 612, 618
		}
	}
}
