// <auto-generated/>
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace HomebreweryShoppingAssistant.Client.Components.Dialog
{
	public partial class DefaultDialog
	{
		[CascadingParameter] MudDialogInstance MudDialog { get; set; }

		void Submit() => MudDialog.Close(DialogResult.Ok(true));
		void Cancel() => MudDialog.Cancel();
	}
}